# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wutianyi/project/LionTrader

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wutianyi/project/LionTrader

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wutianyi/project/LionTrader/CMakeFiles /home/wutianyi/project/LionTrader//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wutianyi/project/LionTrader/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LionTrader

# Build rule for target.
LionTrader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LionTrader
.PHONY : LionTrader

# fast build rule for target.
LionTrader/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LionTrader.dir/build.make CMakeFiles/LionTrader.dir/build
.PHONY : LionTrader/fast

#=============================================================================
# Target rules for targets named UnitTest

# Build rule for target.
UnitTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 UnitTest
.PHONY : UnitTest

# fast build rule for target.
UnitTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/build
.PHONY : UnitTest/fast

src/engine/MdEngine.o: src/engine/MdEngine.cpp.o
.PHONY : src/engine/MdEngine.o

# target to build an object file
src/engine/MdEngine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LionTrader.dir/build.make CMakeFiles/LionTrader.dir/src/engine/MdEngine.cpp.o
.PHONY : src/engine/MdEngine.cpp.o

src/engine/MdEngine.i: src/engine/MdEngine.cpp.i
.PHONY : src/engine/MdEngine.i

# target to preprocess a source file
src/engine/MdEngine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LionTrader.dir/build.make CMakeFiles/LionTrader.dir/src/engine/MdEngine.cpp.i
.PHONY : src/engine/MdEngine.cpp.i

src/engine/MdEngine.s: src/engine/MdEngine.cpp.s
.PHONY : src/engine/MdEngine.s

# target to generate assembly for a file
src/engine/MdEngine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LionTrader.dir/build.make CMakeFiles/LionTrader.dir/src/engine/MdEngine.cpp.s
.PHONY : src/engine/MdEngine.cpp.s

src/engine/TraderEngine.o: src/engine/TraderEngine.cpp.o
.PHONY : src/engine/TraderEngine.o

# target to build an object file
src/engine/TraderEngine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LionTrader.dir/build.make CMakeFiles/LionTrader.dir/src/engine/TraderEngine.cpp.o
.PHONY : src/engine/TraderEngine.cpp.o

src/engine/TraderEngine.i: src/engine/TraderEngine.cpp.i
.PHONY : src/engine/TraderEngine.i

# target to preprocess a source file
src/engine/TraderEngine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LionTrader.dir/build.make CMakeFiles/LionTrader.dir/src/engine/TraderEngine.cpp.i
.PHONY : src/engine/TraderEngine.cpp.i

src/engine/TraderEngine.s: src/engine/TraderEngine.cpp.s
.PHONY : src/engine/TraderEngine.s

# target to generate assembly for a file
src/engine/TraderEngine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LionTrader.dir/build.make CMakeFiles/LionTrader.dir/src/engine/TraderEngine.cpp.s
.PHONY : src/engine/TraderEngine.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LionTrader.dir/build.make CMakeFiles/LionTrader.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LionTrader.dir/build.make CMakeFiles/LionTrader.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LionTrader.dir/build.make CMakeFiles/LionTrader.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

tests/test_match.o: tests/test_match.cpp.o
.PHONY : tests/test_match.o

# target to build an object file
tests/test_match.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/tests/test_match.cpp.o
.PHONY : tests/test_match.cpp.o

tests/test_match.i: tests/test_match.cpp.i
.PHONY : tests/test_match.i

# target to preprocess a source file
tests/test_match.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/tests/test_match.cpp.i
.PHONY : tests/test_match.cpp.i

tests/test_match.s: tests/test_match.cpp.s
.PHONY : tests/test_match.s

# target to generate assembly for a file
tests/test_match.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/UnitTest.dir/build.make CMakeFiles/UnitTest.dir/tests/test_match.cpp.s
.PHONY : tests/test_match.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... LionTrader"
	@echo "... UnitTest"
	@echo "... src/engine/MdEngine.o"
	@echo "... src/engine/MdEngine.i"
	@echo "... src/engine/MdEngine.s"
	@echo "... src/engine/TraderEngine.o"
	@echo "... src/engine/TraderEngine.i"
	@echo "... src/engine/TraderEngine.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... tests/test_match.o"
	@echo "... tests/test_match.i"
	@echo "... tests/test_match.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

